literal = number | string;
list = "[" expr* "]";

expr = tuple_elem | "," expr;
tuple_elem = term | term "+" tuple_elem | term "-" tuple_elem | term "++" tuple_elem;
term = factor | factor "*" term | factor "/" term;
factor = atom | "-" atom;
atom = literal | "(" expr ")" | identifier | list;
